<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <CodeAnalysisRuleSet>InteractiveAutomationToolkitTests.ruleset</CodeAnalysisRuleSet>
        <IsPackable>false</IsPackable>
        <PlatformTarget>x86</PlatformTarget>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\InteractiveAutomationToolkit\InteractiveAutomationToolkit.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Include="stylecop.json" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
        <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
        <PackageReference Include="Skyline.DataMiner.Dev.Automation" Version="10.6.3" />
    </ItemGroup>
</Project>