<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<PlatformTarget>anycpu</PlatformTarget>
		<CodeAnalysisRuleSet>InteractiveAutomationToolkit.ruleset</CodeAnalysisRuleSet>
		<AssemblyName>Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit</AssemblyName>
		<RootNamespace>Skyline.DataMiner.Utils.InteractiveAutomationScript</RootNamespace>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>SkylineCommunications</Authors>
		<Company>Skyline Communications</Company>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageTags>Skyline;DataMiner;GUI</PackageTags>
		<PackageProjectUrl>https://skyline.be/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<Description>Quickly develop Interactive Automation Scripts in DataMiner 10.6.3 and up.</Description>
		<PackageIcon>Icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>10.6.3.1</Version>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="" />
		<None Include="..\LICENSE.txt" Pack="true" PackagePath="" />
		<None Include="nuget\Icon.png" Pack="true" PackagePath="" />
		<None Include="stylecop.json" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="$(MSBuildProjectName)Tests" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
		<PackageReference Include="Skyline.DataMiner.Dev.Automation" Version="10.6.3" />
	</ItemGroup>
	<Target Name="CopyNuGetPackage" AfterTargets="Pack" Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<Copy SourceFiles="$(OutputPath)..\$(PackageId).$(PackageVersion).nupkg" DestinationFolder="C:\Skyline_Data\MyNugets\" />
	</Target>
</Project>
